### ISSUE TITLE
Democracy Now addon for kodi stopped working

### ISSUE THREAD

**Issue by stevesss** [chakravyu/repository.xbmc.chakra#1]
I had been using your addon for months with no problem and all of sudden it no longer works. I have tried installing and reinstalling to no avail. Here is the error message from temp/kodi.log.  
File "/home/osmc/.kodi/addons/plugin.video.democracynow/addon.py", line 31, in main
                                                date = soup.find('div', 'context_header').h2.string.strip()
                                            AttributeError: 'NoneType' object has no attribute 'h2'
                                            -->End of Python script error report<--
06:59:22.755 T:1958817792   ERROR: GetDirectory - Error getting plugin://plugin.video.democracynow/
06:59:22.756 T:1958817792   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.democracynow/) failed

**Comment by cheribhai** [comment]
Plan to have a look and hopefully fix it this weekend. 
Seems to be due to changes on the DN! website.

**Comment by cheribhai** [comment]
Addon updated to latest DN website.
Please update repository to get the changes.

**Comment by cheribhai** [comment]
Closing as fixed.
